config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
	resources :cities do
    resources :places
  end
	resources :places do
    resources :spots 
    get '/spots/category/:category' => 'spots#category'
  end
  resources :spots do
    resources :posts, except: [:index] do
      post "like", to: "likes#like_post_toggle"
    end
    post "like", to: "likes#like_spot_toggle"
    get 'map' => 'spots#map'
  end

  get '/mypage' => 'mypage#my'
  get '/user/:id' => 'mypage#user'
  get '/mypage/:category' => 'mypage#my'

  get '/spots/category/:category' => 'spots#category'
  get '/welcome/index'
  get '/map' => 'spots#all_map'
  get '/map/:category' => 'spots#all_map'

  root 'welcome#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord
	enum category: {do:0, see:1, eat:2, sleep:3}

	validates :name, presence: true
	validates :category, presence: true

	belongs_to :user
	belongs_to :place

	has_many :posts, dependent: :destroy
	has_many :likes, dependent: :destroy

	has_many :spot_reads, dependent: :destroy
	has_many :spot_rates, dependent: :destroy
	
	has_many :liked_users, through: :likes, source: :user
	has_many :read_users, through: :spot_reads, source: :user
	has_many :rate_posts, through: :spot_rates, source: :post
	
	mount_uploader :picture, PictureUploader

	geocoded_by :address
	after_validation :geocode

	def json_data
		{ type: "Spot", name: name, children: nil, id: id } 
	end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, only: [:show, :edit, :update, :destroy, :map]
  before_action :place_select, only: [:index, :category, :show, :new, :create]
  before_action :place_spots, only: [:show]

  def category
    @post = Post.new
    if @place_id
      @category_spots = Spot.where(place_id: @place_id, category: params[:category])
    else
      @category_spots = Spot.where(category: params[:category])
    end
  end
  
  def index
    @spots = @place_id ? Spot.where(place_id: @place_id) : Spot.all
  end

  def new
   	@spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user
    @spot.save ? (redirect_to @spot) : (render 'new')
  end

  def show
    @spotlike = Like.where(spot_id: @spot.id, post_id: nil)
    @post = Post.new
    @hash = Gmaps4rails.build_markers(@spot) do |spot, marker|
    marker.lat spot.latitude
    marker.lng spot.longitude
    marker.title   "i'm the title"
    marker.infowindow render_to_string(
      :partial => "/spots/info", 
      :locals => {spot: spot})
    end

    # if !SpotRead.find_by(user: current_user, spot_id: params[:id])
    #   if current_user.posts.count * 5 >= current_user.read_spots.count
    #     SpotRead.create(user: current_user, spot_id: params[:id])
    #   else        
    #     redirect_to spots_path
    #   end
    # end
  end

  def map
    @hash = Gmaps4rails.build_markers(@spot) do |spot, marker|
    marker.lat spot.latitude
    marker.lng spot.longitude
    marker.title   "i'm the title"
    marker.infowindow render_to_string(
      :partial => "/spots/info", 
      :locals => {spot: spot})
    end
  end

  def all_map
    if params[:category]
      @spots = Spot.where(category: params[:category])
    else 
      @spots = Spot.all
    end
    @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
    marker.lat spot.latitude
    marker.lng spot.longitude
    marker.title   "i'm the title"
    marker.infowindow render_to_string(
      :partial => "/spots/info", 
      :locals => {spot: spot})
    end
  end

  def edit
  end

  def update
    @spot.update(spot_params) ? (redirect_to @spot) : (render 'edit')
  end

  def destroy
    @spot.destroy
    redirect_to spots_path
  end

  private
  def spot_params
	  params.require(:spot).permit(:name, :user, :place_id, :category, :picture, :picture_cache, :latitude, :longitude,:address)
  end

  def set_spot
    if params[:spot_id]
      @spot = Spot.find(params[:spot_id])
    else params[:id]
      @spot = Spot.find(params[:id])
    end
  end

  def place_select
    @place_id = params[:place_id]
    @spot_categories = Spot.categories.keys
    @places = Place.all
  end

  def place_spots
    if @place_id
      if params[:category]
        @spots = Spot.where(place_id: @place_id, category: params[:category])
      else
        @spots = Spot.where(place_id: @place_id)
      end
    else
      @spots = Spot.all
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_category.html.erb
<div class="row">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
		<div class="dropdown">
		  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		    Places
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
		  	<li><%= link_to 'All', spots_path %></li>
		  	<% @places.each do |place| %>
		  		<li><%= link_to "#{place.name}", place_spots_path(place) %></li>
		    <% end %>
		  </ul>
		</div>
	</div>
	<div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
		<ul class="nav nav-tabs">
			<% if !params[:category] %>
			<li role="presentation" class="active">
			<% else %>
			<li role="presentation">
			<% end %>
				<%= link_to "All", @place_id ?
				"/places/#{@place_id}/spots" : "/spots" %>
			</li>
			<% @spot_categories.each do |category| %>
				<% if category == params[:category] %>
				<li role="presentation" class="active">
				<% else %>
				<li role="presentation">
				<% end %>
						<%= link_to "#{category}", @place_id ? 
						"/places/#{@place_id}/spots/category/#{category}" : "/spots/category/#{category}" %>	
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/spots/_form.html.erb
<%= simple_form_for(@spot) do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control' }, label: false, placeholder: 'Name' %>
  </div>
  <div class="form-group">
    <%= f.input :address, input_html: { class: 'form-control' }, label: false, placeholder: '주소' %>
  </div>
  <% if @place_id %>
    <p>Place : <strong><%= Place.find(@place_id).name %></strong></p>
    <%= f.hidden_field :place_id, value: "#{@place_id}" %>
  <% else %>
    <div class="form-group">
      <%= f.collection_radio_buttons :place_id, Place.all, :id, :name %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.collection_radio_buttons :category, Spot.categories, :first, :first %>
  </div>
  <div class="form-group">
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <%= f.button :submit, class: 'btn btn-default'%>
<% end %>

app/views/spots/_info.html.erb
<%= link_to spot_path(spot) do %>
<strong><%= spot.name %></strong><br>
<%= spot.address %>
<% end %>

app/views/spots/_map.html.erb
<script type="text/javascript">
	handler = Gmaps.build('Google');
	
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);	  	
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	  handler.getMap().setZoom(10);
	});
</script>

app/views/spots/_show.html.erb
<%= link_to spot_path(spot) do %>
	<strong><%= spot.name%></strong><br>
<% end %>
Category : <%= spot.category %> | Status : <%= spot.status %><br>
<%= spot.likes.size%>명이 좋아합니다.
<% if current_user.is_postlike?(spot) %>
    <%= link_to "좋아요 취소", spot_like_path(spot), method: "post" %>
<% else %>
    <%= link_to "좋아요", spot_like_path(spot), method: "post" %>
<% end %>

<div class="text-right">
	<%= link_to 'Edit', edit_spot_path(spot) %> | 
	<%= link_to 'Delete', spot_path(spot), method: :delete %>
</div>

<hr>

<% spot.posts.all.order('created_at desc').each do |post| %>
	<div>
		<%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
		<strong><%= post.user.name %></strong><br>
		<%= post.body %><br>
		<%= post.likes.size%>명이 좋아합니다.<br>
		<% if current_user.is_postlike?(post) %>
		    <%= link_to "좋아요 취소", spot_post_like_path(@spot, post), method: "post" %>
		<% else %>
		    <%= link_to "좋아요", spot_post_like_path(@spot, post), method: "post" %>
		<% end %>

		<% if post.user == current_user %>
			<div class="text-right">
				<%= link_to 'Read detail', spot_post_path(@spot, post) %> | 
				<%= link_to 'Edit', edit_spot_post_path(@spot, post) %> | 
				<%= link_to 'Delete', spot_post_path(@spot, post), method: :delete %>
		<% end %>
		</div>
	</div>
	<% if post.user == current_user %>
		<div class="text-right">
			<%= link_to 'Read detail', spot_post_path(spot, post) %> | 
			<%= link_to 'Edit', edit_spot_post_path(spot, post) %> | 
			<%= link_to 'Delete', spot_post_path(spot, post), method: :delete %>
		</div>
	<% end %>
<% end %>

app/views/spots/_spot.html.erb
<div style="min-height: 200px;">
	<div class="col-md-8">
		<%= link_to "#{spot.name}", spot_path(spot), style: "font-size: 20px;" %>
		<%= link_to spot_map_path(spot), class: "font-12", style:'text-decoration:none; margin-left: 10px; color: black;' do %>
			<%= image_tag("map", size: "20x20", style: "margin-top: -10px;") %> 지도보기
		<% end %>
		<br>
		<%= spot.address %>
	</div>
	<div class="col-md-4 text-right">
		<span class="label label-primary"><%= spot.place.city.name %></span>
		<span class="label label-success"><%= spot.place.name %></span>
		<span class="label label-info"><%= spot.category %></span>
		<hr style="margin: 15px 0 10px 0;">
		<div class="font-12">
			<% if current_user.is_spotlike?(spot) %>
		    <%= link_to image_tag("heart_filled", size: "15x15"), spot_like_path(spot), method: "post" %>
			<% else %>
		    <%= link_to image_tag("heart", size: "15x15"), spot_like_path(spot), method: "post" %>
			<% end %>
			<%= spot.likes.where(post_id:nil).size%>명이 좋아합니다.<br><br>
			<%= link_to 'Spots list', spots_path %> | 
			<% if current_user == spot.user %>
				
				<%= link_to 'Edit', edit_spot_path(spot) %> | 
				<%= link_to 'Delete', spot_path(spot), method: :delete %>
			<% end %>
		</div>
	</div>

</div>
<hr>

<div>
	<div class="mu-10 mb-10 ml-10" style="margin-bottom: 20px;">
		<strong style="font-size: 15px">포스트   </strong>
		<span style="font-size: 10px">Post</span> 
	</div>
	<% spot.posts.all.order('created_at desc').each do |post| %>
		<%= image_tag(post.user.image, size: '20x20', style:'border-radius: 3px; vertical-align:medium; margin-top: -4px;') if current_user.image %>
		<strong><%= post.user.name %></strong>
		<span style="font-size: 12px;"><%= post.user.created_at.strftime("20%y/%m/%d") %></span>

		<div class="text-right font-12">
			<%= link_to 'Read detail', spot_post_path(spot, post) %> 
			<% if post.user == current_user %>
				 | <%= link_to 'Edit', edit_spot_post_path(spot, post) %> | 
				<%= link_to 'Delete', spot_post_path(spot, post), method: :delete %>
			<% end %>
		</div>
		
		<br><br>
		<%= post.body.html_safe %><br>
		<div class="font-12">
		<strong><%=post.title%></strong><br>
		<% if current_user.is_postlike?(post) %>
		    <%= link_to image_tag("heart_filled", size: "15x15"), spot_post_like_path(@spot, post), method: "post" %>
		<% else %>
		    <%= link_to image_tag("heart", size: "15x15"), spot_post_like_path(@spot, post), method: "post" %>
		<% end %>
		<%= post.likes.size%>명이 좋아합니다.
		</div>
		<hr>
	<% end %>
</div>

app/views/spots/_spots.html.erb
<% @spots.each do |spot| %>
  <div class="thumbnails-image-list">
    <%= link_to spot_path(spot) do %>
      <div class="thumbnail thumbnail-image-box-small" style="background-image: url(<%= spot.picture %>);">
  			<div class="caption">
      		<h3><%= spot.name%></h3>
				</div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spots/all_map.html.erb
<% @colorbar_map = true %>

<div class="w-100">
  <div id="map" class="w-100" style='height: 300px;'></div>
</div>

<%= render "map" %>

app/views/spots/category.html.erb
<h4>
  Spots in
  <% if @place_id %>
    <%= link_to "#{Place.find(@place_id).name}", place_path(@place_id) if @place_id %>
  <% else %>
    All places
  <% end %>
  | <%= params[:category] %>
</h4>

<div class="row">
	<% @category_spots.each do |spot| %>
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <%= link_to spot_path(spot) do %>
          <div class="thumbnail thumbnail-image-box" style="background-image: url(<%= spot.picture.url %>);">
      			<div class="caption">
          		<h3><%= spot.name%></h3>
    				</div>
          </div>
        <% end %>
     </div>
	<% end %>
</div>

app/views/spots/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', spot_path(@spot) %>

app/views/spots/index.html.erb
<%= render "category" %>
<h4>
  Spots in
  <% if @place_id %>
    <%= link_to "#{Place.find(@place_id).name}", place_path(@place_id) if @place_id %>
  <% else %>
    All places
  <% end %>
</h4>
<div class="row">
	<% @spots.each do |spot| %>
    <div class="col-sm-6 col-md-6">
      <%= link_to spot_path(spot) do %>
        <div class="thumbnail thumbnail-image-box" style="background-image: url(<%= spot.picture %>);">
    			<div class="caption">
        		<h3><%= spot.name%></h3>
  				</div>
        </div>
      <% end %>
    </div>
	<% end %>
</div>
<% if @place_id %>
  <%= link_to 'Spot 만들기', new_place_spot_path(@place_id), class: 'btn btn-default' %>
<% else %>
<%= link_to 'Spot 만들기', new_spot_path, class: 'btn btn-default' %>
<% end %>

app/views/spots/map.html.erb
<% @colorbar_map = true %>

<%= link_to spot_path(@spot) do %>
	<h4><%= @spot.name%></h4>
<% end %>
<span class="label label-primary"><%= @spot.place.city.name %></span>
<span class="label label-success"><%= @spot.place.name %></span>
<span class="label label-info"><%= @spot.category %></span><br>
<% if current_user.is_spotlike?(@spot) %>
    <%= link_to image_tag("heart", size: "15x15"), spot_like_path(@spot), method: "post" %>
<% else %>
    <%= link_to "좋아요", spot_like_path(@spot), method: "post" %>
<% end %>
<%= @spot.likes.size%>명이 좋아합니다.


<div class="w-100">
  <div id="map" class="w-100" style='height: 300px;'></div>
</div>

<%= render "map" %>

app/views/spots/new.html.erb
<%= render 'form' %>

app/views/spots/show.html.erb
<%= render partial: 'spot', locals: {spot: @spot} %>
<%= render 'posts/form' %>
	
<script type="text/javascript">
	handler = Gmaps.build('Google');
	
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);	  	
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	  handler.getMap().setZoom(10);
	});
</script>