config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
	resources :cities do
    resources :places
  end
	resources :places do
    resources :spots 
    get '/spots/category/:category' => 'spots#category'
  end
  resources :spots do
    resources :posts, except: [:index] do
      post "like", to: "likes#like_post_toggle"
    end
    post "like", to: "likes#like_spot_toggle"
    get 'map' => 'spots#map'
  end

  get '/mypage' => 'mypage#my'
  get '/user/:id' => 'mypage#user'
  get '/mypage/:category' => 'mypage#my'

  get '/spots/category/:category' => 'spots#category'
  get '/welcome/index'
  get '/map' => 'spots#all_map'
  get '/map/:category' => 'spots#all_map'

  root 'welcome#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :name, presence: true

	has_many :places
	
	mount_uploader :picture, PictureUploader

	def json_data
		{ type: "City", name: name, children: places.map{|place| place.json_data}, id: id } 
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_city, only: [:show, :edit, :update, :destroy]
  def index
  	@cities = City.all
  end

  def new
  	@city = City.new
  end

  def create
  	@city = City.new(city_params)
  	@city.save ? (redirect_to @city) : (render 'new')
  end

  def show
    @places = @city.places.all
    @list = Array.new
    @places.each {|place| @list << place}
    @list << @city
    @hash = Gmaps4rails.build_markers(@list) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

  def edit
  end

  def update
  	@city.update(city_params) ? (redirect_to @city) : (render 'edit')
  end

  def destroy
  	@city.destroy
  	redirect_to cities_path
  end

  private
  def city_params
  	params.require(:city).permit(:name, :latitude, :longitude, :address,:picture)
  end

  def set_city
  	@city = City.find(params[:id])
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= simple_form_for(@city) do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control' }, label: false, placeholder: '도시명' %>
  </div>
   <div class="form-group">
    <%= f.input :address, input_html: { class: 'form-control' }, label: false, placeholder: '주소' %>
  </div>

  <div class="form-group">
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>

  <%= f.button :submit, class: 'btn btn-default'%>
<% end %>

app/views/cities/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', city_path(@city) %>

app/views/cities/index.html.erb
<h4>Cities</h4>
<% @cities.each do |city| %>
	<div class="well">
	<%= link_to city_path(city) do %>
		<strong><%= city.name%></strong><br>
	<% end %>
	위도 : <%= city.latitude %>
	경도 : <%= city.longitude %>
	</div>
<% end %>

<%= link_to 'City 만들기', new_city_path, class: 'btn btn-default' %>

app/views/cities/new.html.erb
<%= render 'form' %>

app/views/cities/show.html.erb
<h2><%= @city.name %></h2>
위도 : <%= @city.latitude %><br>
경도 : <%= @city.longitude %><br>
picture : <%=image_tag(@city.picture)%>
<div class="text-right">
	<%= link_to 'Go to cities', cities_path %> | 
	<%= link_to 'Edit', edit_city_path(@city) %> | 
	<%= link_to 'Delete', city_path(@city), method: :delete %>
</div>
<hr>
<h4>Places in <%= @city.name %></h4>
<% @city.places.each do |place| %>
	<div class="well">
		<strong><%= link_to "#{place.name}", place_path(place) %></strong><br>

	</div>
<% end %>
<%= link_to "#{@city.name} place 작성", new_city_place_path(@city) %>

<hr>

<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyAPFLuE2iKv8B3egGibg3z9q8jQosNxD0w"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<div style='width: 800px;'>
  <div id="map" style='width: 1150px; height: 500px;'></div>
</div>
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ 
		provider: {
		}, 
		internal: {
			id: 'map'
		}}, 
		function(){
		  markers = handler.addMarkers(<%=raw @hash.to_json %>);
		  handler.bounds.extendWith(markers);
		  handler.fitMapToBounds();
		  handler.getMap().setZoom(11);
	});
</script>