config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
	resources :cities do
    resources :places
  end
	resources :places do
    resources :spots 
    get '/spots/category/:category' => 'spots#category'
  end
  resources :spots do
    resources :posts, except: [:index] do
      post "like", to: "likes#like_post_toggle"
    end
    post "like", to: "likes#like_spot_toggle"
    get 'map' => 'spots#map'
  end

  get '/mypage' => 'mypage#my'
  get '/user/:id' => 'mypage#user'
  get '/mypage/:category' => 'mypage#my'

  get '/spots/category/:category' => 'spots#category'
  get '/welcome/index'
  get '/map' => 'spots#all_map'
  get '/map/:category' => 'spots#all_map'

  root 'welcome#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :name, presence: true
	
	belongs_to :city
	has_many :spots

	mount_uploader :picture, PictureUploader

	def json_data
		{ type: "Place", name: name, children: spots.map{|spot| spot.json_data}, id: id } 
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :city_select, only: [:new, :create]

  def index
    @places = Place.all
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
    marker.lat place.latitude
    marker.lng place.longitude
    end
    
  end

  def new
  	@place = Place.new
  end

  def create
   	@place = Place.new(place_params)
    @place.save ? (redirect_to @place) : (render 'new')
  end

  def show
    @spots = @place.spots.all
    @list = Array.new
    @spots.each {|spot| @list << spot}
    @list << @place
    @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
    marker.lat spot.latitude
    marker.lng spot.longitude
    marker.title   "i'm the title"
    marker.infowindow render_to_string(
      :partial => "/spots/info", 
      :locals => {spot: spot})
    end
  end

  def edit
  end

  def update
  	@place.update(place_params) ? (redirect_to @place) : (render 'edit')
  end

  def destroy
  	@place.destroy
  	redirect_to places_path
  end

  private
  def place_params
   	params.require(:place).permit(:name, :latitude, :longitude, :city_id, :address, :picture, :picture_cache)
  end

  def set_place
    @place = Place.find(params[:id])
  end

  def city_select
    @city_id = params[:city_id]
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control' }, label: false, placeholder: '장소 이름' %>
  </div>
  <div class="form-group">
    <%= f.input :address, input_html: { class: 'form-control' }, label: false, placeholder: '주소' %>
  </div>
  <% if @city_id %>
    <p>City : <strong><%= City.find(@city_id).name %></strong></p>
    <%= f.hidden_field :city_id, value: "#{@city_id}" %>
  <% else %>
    <div class="form-group">
      <%= f.collection_radio_buttons :city_id, City.all, :id, :name %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <%= f.button :submit, class: 'btn btn-default'%>
<% end %>

app/views/places/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', place_path(@place) %>

app/views/places/index.html.erb
<h4>Places</h4>

<br><br>
<div class="row">
  <% @places.each do |place| %>
    <div class="col-sm-6 col-md-6">
      <%= link_to place_spots_path(place) do %>
        <div class="thumbnail thumbnail-image-box" style="background-image: url(<%= place.picture.url %>);">
    			<div class="caption">
        		<h3 style="text-align:center; font-size: 30px;"><%= place.name%></h3>
  				</div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Place 만들기', new_place_path, class: 'btn btn-default' %>

app/views/places/new.html.erb
<%= render 'form' %>

app/views/places/show.html.erb
<h2><%= @place.name %></h2>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 300px;'></div>
</div>
소속 City : <%= link_to @place.city.name, city_path(@place.city) %><br>
picture : <%=image_tag(@place.picture)%>
<div class="text-right">
	<%= link_to 'Go to places', places_path %> | 
	<%= link_to 'Edit', edit_place_path(@place) %> | 
	<%= link_to 'Delete', place_path(@place), method: :delete %>
</div>
<hr>
<p>
	<strong>Spots in <%= @place.name %></strong> | 
	<%= link_to "#{@place.name} spot 작성", new_place_spot_path(@place) %>
</p>
<% @place.spots.each do |spot| %>
	<div class="col-md-6 col-lg-6 col-sm-6">
		<%= link_to spot_path(spot) do %>
			<div class="thumbnail text-center" style="height: 100px;">
				<strong><%= spot.name %></strong>
			</div>
		<% end %>
	</div>
<% end %>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%=raw @hash.to_json %>);	  	
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	  handler.getMap().setZoom(10);
	});
</script>