config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
	resources :cities do
    resources :places
  end
	resources :places do
    resources :spots 
    get '/spots/category/:category' => 'spots#category'
  end
  resources :spots do
    resources :posts, except: [:index] do
      post "like", to: "likes#like_post_toggle"
    end
    post "like", to: "likes#like_spot_toggle"
    get 'map' => 'spots#map'
  end

  get '/mypage' => 'mypage#my'
  get '/user/:id' => 'mypage#user'
  get '/mypage/:category' => 'mypage#my'

  get '/spots/category/:category' => 'spots#category'
  get '/welcome/index'
  get '/map' => 'spots#all_map'
  get '/map/:category' => 'spots#all_map'

  root 'welcome#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :name, presence: true

	has_many :places
	
	mount_uploader :picture, PictureUploader

	def json_data
		{ type: "City", name: name, children: places.map{|place| place.json_data}, id: id } 
	end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :name, presence: true
	
	belongs_to :city
	has_many :spots

	mount_uploader :picture, PictureUploader

	def json_data
		{ type: "Place", name: name, children: spots.map{|spot| spot.json_data}, id: id } 
	end
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, presence: true

	belongs_to :user
	belongs_to :spot

	has_one :spot_rate
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	serialize :imageurls, Array

	mount_uploader :picture, CkeditorPictureUploader

	before_save do
		if body.present?
			self.imageurls = Nokogiri::HTML.fragment(body).css('img').map{|img| img.attribute('src')}.collect(&:to_s)
		end
	end
end

app/models/saying.rb
class Saying < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
	enum category: {do:0, see:1, eat:2, sleep:3}

	validates :name, presence: true
	validates :category, presence: true

	belongs_to :user
	belongs_to :place

	has_many :posts, dependent: :destroy
	has_many :likes, dependent: :destroy

	has_many :spot_reads, dependent: :destroy
	has_many :spot_rates, dependent: :destroy
	
	has_many :liked_users, through: :likes, source: :user
	has_many :read_users, through: :spot_reads, source: :user
	has_many :rate_posts, through: :spot_rates, source: :post
	
	mount_uploader :picture, PictureUploader

	geocoded_by :address
	after_validation :geocode

	def json_data
		{ type: "Spot", name: name, children: nil, id: id } 
	end
end

app/models/spot_rate.rb
class SpotRate < ApplicationRecord
	belongs_to :spot
	belongs_to :post
end

app/models/spot_read.rb
class SpotRead < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :spots, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :sayinygs, dependent: :destroy
  has_many :spot_reads, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :read_spots, through: :spot_reads, source: :spot
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    end
  end
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  def is_spotlike?(spot)
    Like.find_by(user_id: self.id,spot_id: spot.id, post_id: nil).present?
  end
  def is_postlike?(post)
    Like.find_by(user_id: self.id,post_id: post.id, spot_id: post.spot.id).present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def like_spot_toggle
		@like = Like.find_by(user_id: current_user.id, spot_id: params[:spot_id])
		if @like.nil?
			Like.create(user_id: current_user.id, spot_id: params[:spot_id], post_id: nil)
		else
			@like.destroy
		end
		redirect_to :back
	end
	def like_post_toggle
		@like = Like.find_by(user_id: current_user.id, post_id: params[:post_id], spot_id: params[:spot_id])
		if @like.nil?
			Like.create(user_id: current_user.id, post_id: params[:post_id], spot_id: params[:spot_id])
		else
			@like.destroy
		end
		redirect_to :back
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end
  
  def new
    @post = @spot ? @spot.posts.new : Post.new
    gon.location_data = City.all.map{|city| city.json_data}
  end

  def create
  	@post = @spot.posts.create(post_params)
  	@post.user = current_user
    if @post.save
      redirect_to @spot
    else
      gon.location_data = City.all.map{|city| city.json_data}
      render 'new'
    end
  end

  def show 
  end

  def edit
  end

  def update
    @post.update(post_params) ? (redirect_to @spot) : (render 'edit')
  end

  def destroy
    @post.destroy
    redirect_to spot_path(@spot)
  end

  private
  def post_params
  	params.require(:post).permit(:body, :user,:picture, :title)
  end

  def set_spot
    @spot = Spot.find(params[:spot_id]) if params[:spot_id]
  end

  def set_post
    @post = params[:spot_id] ? @spot.posts.find(params[:id]) : Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/asks/edit.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/layouts/_color.html.erb
<div class="row">
	<div class="text-center">
		<% if params[:place_id] %>
			<%= link_to 'All', place_spots_path(@place_id), class: "navbar-link-box navbar-link-box-all" %>
		<% elsif @colorbar_mypage %>
			<%= link_to 'All', mypage_path, class: "navbar-link-box navbar-link-box-all" %>
		<% elsif @colorbar_map %>
			<%= link_to 'All', map_path, class: "navbar-link-box navbar-link-box-all" %>
		<% else %>
			<%= link_to 'All', spots_path, class: "navbar-link-box navbar-link-box-all" %>
		<% end %>
		
		<!-- <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9"> -->
		
		<% @spot_categories = Spot.categories.keys %>
		<% @spot_categories.each do |category| %>
			<% if params[:place_id] %>
				<%= link_to "#{category}", "/places/#{@place_id}/spots/category/#{category}", class: "navbar-link-box navbar-link-box-#{category}" %>
			<% elsif @colorbar_mypage %>
				<%= link_to "#{category}", "/mypage/#{category}", class: "navbar-link-box navbar-link-box-#{category}" %>
			<% elsif @colorbar_map %>
				<%= link_to "#{category}", "/map/#{category}", class: "navbar-link-box navbar-link-box-#{category}" %>
			<% else %>
				<%= link_to "#{category}", "/spots/category/#{category}", class: "navbar-link-box navbar-link-box-#{category}" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-head">
<div class="row">
  <div class="col-xs-12 col-md-8 col-lg-8 navbar-head-left" style="margin:0;">
    <%= link_to root_path do %>
      <%= image_tag "logo", class: "navbar-logo-image"%>
    <% end %> 
  </div>
  <div class="col-xs-12 col-md-4 col-lg-4 navbar-head-right">
  	<% if user_signed_in? %>
      <%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
      <%= current_user.name %>
  		<%= link_to '로그아웃', destroy_user_session_path, method: :delete %>
  	<% else %>
    
    
      <%= link_to user_facebook_omniauth_authorize_path do %>
        <%= image_tag "login_fb", size: "150x30", class: "navbar-login-fb" %>
      <% end %>
   
  </div>
      
  	<% end %>
  </div>
</div>
</div>

app/views/layouts/_white.html.erb
<div class="row">
	<div class="navbar-link-icon">
		<%= link_to image_tag("home", size: "20x20"), root_path %>
	</div>
	<div class="navbar-link-icon">
		<%= link_to image_tag("cities", size: "20x20"), cities_path %>
	</div>
	<div class="navbar-link-icon">
		<%= link_to image_tag("search", size: "20x20"), root_path %>
	</div>
	<div class="navbar-link-icon">
		<%= link_to image_tag("map", size: "20x20"), map_path %>
	</div>
	<div class="navbar-link-icon">
		<%= link_to image_tag("heart", size: "20x20"), mypage_path %>
	</div>
</div>
<hr style="margin:7px 0 0;">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Browny</title>
    <%= include_gon %>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?v=3&key=AIzaSyAPFLuE2iKv8B3egGibg3z9q8jQosNxD0w"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  </head>
  <body>
    <nav class="white-navbar text-center">
      <%= render 'layouts/white' %>  
      <%= render 'layouts/color' %>
    </nav>
    <div class="container">
      <div class="row" style="margin-top: 50px;">
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-1">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" style="padding-top: 30px;">
          <%= yield %>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-1">
        </div>
      </div>
    </div>   

    <% if @include_select_location_js %>
      <%= javascript_include_tag 'posts/select_location' %>
    <% end %>
  </body>
</html>